[package]
name = "RenegadeX-Launcher"
version = "0.9.0"
authors = ["SonnyX"]
edition = "2018"
build = "windows.rs"
exclude = ["dom", "new", "dom/**", "new/**", "RenX-Launcher.zip", "sciter.dll", "SelfUpdateExecutor.exe", "RenegadeX-Launcher.ini", "RenegadeX-Launcher"]

[dependencies]
hyper = "^0.12.27"
hyper-tls = "^0.3.2"
tokio = "^0.1.18"
tokio-tls = "^0.2.1"
tokio-xmpp = "^1.0.0"
xmpp-parsers = "0.13.0"
native-tls = "^0.2"
tokio-reactor = "^0.1.9"
url = "^1.7.2"
futures = "^0.1.27"
sciter-rs = "^0.5.45"
renegadex_patcher = { git = "https://github.com/SonnyX/RenegadeX-patcher-lib" }
rust-ini = "^0.13.0"
single-instance = "^0.1.1"
socket2 = "^0.3.8"
rand = "^0.6.5"
percent-encoding = "^1.0.1"
unzip = "^0.1.0"

[target.'cfg(windows)'.build-dependencies]
winres = "^0.1.8"

[package.metadata.winres]
OriginalFilename = "RenegadeX_Launcher.exe"
FileDescription = "Launcher for RenegadeX"
LegalCopyright = "Copyright © 2019"
