[package]
name = "RenegadeX-Launcher"
version = "0.1.0"
authors = ["SonnyX"]
edition = "2018"
build = "windows.rs"

[dependencies]
reqwest = "0.9.5"
sciter-rs = "0.5.45"
renegadex_patcher = { git = "https://github.com/SonnyX/RenegadeX-patcher-lib" }
rust-ini = "0.13.0"
irc = "0.13.6"
single-instance = "0.1.1"
socket2 = "0.3.8"
rand = "0.6.5"
deunicode = "1.0.0"
percent-encoding = "1.0.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.8"

[package.metadata.winres]
OriginalFilename = "RenegadeX_Launcher.exe"
FileDescription = "Launcher for RenegadeX"
LegalCopyright = "Copyright © 2019"
