name: Linux

on:
  pull_request:
  push:
    branches:
      - master
    paths:
    - '.github/workflows/linux.yml'
    - 'backend/**/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update dependencies
      run: sudo apt-get install libgtk-3-dev && (cargo update || (sh fix-build-issues.sh && cargo update))
    - name: Build
      run: cd backend && cargo build --release --verbose