name: Publish new version

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup update --no-self-update stable && rustup default stable
    - run: rustup target add i686-pc-windows-msvc

    - name: build
      run: cargo build --manifest-path="windows-target/Cargo.toml" --target-dir="windows-target" --target=i686-pc-windows-msvc --release

    - name: Package Files
      shell: pwsh
      run: >
        cp windows-target/i686-pc-windows-msvc/release/RenegadeX-Launcher.exe "windows-target/Renegade X Launcher.exe";
        $compress = @{
          Path = "windows-target/Renegade X Launcher.exe", "windows-target/RenegadeX-folder-permissions.exe", "windows-target/sciter.dll", "windows-target/SelfUpdateExecutor.exe", "dom";
          CompressionLevel = "Optimal";
          DestinationPath = "windows-target/RenX-Launcher.zip"
        };
        Compress-Archive @compress

    - uses: actions/upload-artifact@v2
      with:
        name: RenX-Launcher
        path: windows-target/RenX-Launcher.zip

    - name: Upload ftp
      uses: bayssmekanique/action-simple-file-upload@v1
      with:
        host: ${{ secrets.FTP_URL }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        src: windows-target/RenX-Launcher.zip
        dest: renxdownloads/RenX-Launcher.zip

    - name: Update versions
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: jq '.launcher={"version_name":.launcher.version_name,"version_number":110,"patch_url":"https://renxdownloads.b-cdn.net/"}' static.renegade-x.com/data/launcher_data/version/launcher.json > static.renegade-x.com/data/launcher_data/version/launcher.json
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.SSH_KEY}}