name: Publish new version

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup update --no-self-update stable && rustup default stable
    - run: rustup target add i686-pc-windows-msvc

    - name: build
      run: cargo build --manifest-path="windows-target/Cargo.toml" --target-dir="windows-target" --target=i686-pc-windows-msvc --release

    - name: Package Files
      shell: bash
      run: >
        cp ./windows-target/i686-pc-windows-gnu/release/RenegadeX-Launcher.exe "./windows-target/Renegade X Launcher.exe" &&
        zip -j9 windows-target/RenX-Launcher "windows-target/Renegade X Launcher.exe" "windows-target/sciter.dll" "windows-target/SelfUpdateExecutor.exe" &&
        zip -9 windows-target/RenX-Launcher -r "dom"

    - uses: actions/upload-artifact@v2
      with:
        name: RenX-Launcher
        path: windows-target/RenX-Launcher.zip

    - name: Upload File
      shell: bash
      run: curl -T windows-target/RenX-Launcher.zip ${{ secrets.FTP_URL }} --user ${{ secrets.FTP_USER }}:${{ secrets.FTP_PASSWORD }}