name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update dependencies
      run: sudo apt-get install libgtk-3-dev && (cargo update || (sh fix-build-issues.sh && cargo update))
    - name: Build
      run: cargo build --release --verbose
    - name: Build Windows
      run: sh package-windows.sh
