name: Test

on:
  workflow_dispatch:

jobs:
  commit-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Update versions
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: >
         echo "hello" > static.renegade-x.com/data/launcher_data/version/launcher-try.json
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.SSH_KEY }}
