name: Windows

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Update dependencies
      run: sudo apt install --no-install-recommends gcc-mingw-w64-i686

    - name: Install latest toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: i686-pc-windows-gnu
          override: true

    - name: Update Cargo
      run: cargo update --manifest-path="windows-target/Cargo.toml"

    - name: Build
      run: cargo build --manifest-path="windows-target/Cargo.toml" --target-dir="windows-target" --target=i686-pc-windows-gnu --release

    - name: Package Files
      run: >
        cp ./windows-target/i686-pc-windows-gnu/release/RenegadeX-Launcher.exe "./windows-target/Renegade X Launcher.exe" &&
        zip -j9 windows-target/RenX-Launcher "windows-target/Renegade X Launcher.exe" "windows-target/sciter.dll" "windows-target/SelfUpdateExecutor.exe" &&
        zip -9 windows-target/RenX-Launcher -r "dom"

    - uses: actions/upload-artifact@v2
      with:
        name: RenX-Launcher
        path: windows-target/RenX-Launcher.zip
