name: Windows

on:
  pull_request:
  push:
    branches:
      - master
    paths:
    - '.github/workflows/windows.yml'
    - 'src/**'
    - 'windows-target/Cargo.toml'
    - 'windows-target/Cargo.lock'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup update --no-self-update stable && rustup default stable
    - run: rustup target add i686-pc-windows-msvc

    - name: build
      run: cargo build --manifest-path="windows-target/Cargo.toml" --target-dir="windows-target" --target=i686-pc-windows-msvc --release