[package]
name = "RenegadeX-Launcher"
version = "0.9.12"
authors = ["SonnyX"]
edition = "2018"
build = "windows.rs"
exclude = ["target-windows/**", "target/**", "C:", "C:/**", "dom", "new", "dom/**", "new/**", "RenX-Launcher.zip", "RenX-Launcher.exe", "sciter.dll", "SelfUpdateExecutor.exe", "RenegadeX-Launcher.ini", "RenegadeX-Launcher"]

[[bin]]
name = "RenegadeX-Launcher"
path = "../src/main.rs"

[dependencies]
hyper = "^0.13.6"
hyper-tls = "^0.4.1"
tokio = { version = "0.2", features = ["full"] }
tokio-tls = "^0.2.1"
native-tls = "^0.2"
tokio-reactor = "^0.1.9"
url = "^2.1.0"
futures = "^0.3.5"
sciter-rs = "^0.5.50"
renegadex_patcher = { git = "https://github.com/SonnyX/RenegadeX-patcher-lib" }
rust-ini = "^0.13.0"
single-instance = "^0.1.1"
socket2 = "^0.3.8"
rand = "^0.7.0"
percent-encoding = "^2.1.0"
unzip = "^0.1.0"
dirs = "^3.0.0"

[build-dependencies]
embed-resource = "1.3.0"


[profile.release]
opt-level = 'z'
lto=true
